#!/usr/bin/env python3
"""Regenerate test/host/cryptvec.h from Python hashlib."""
import hashlib, random, sys
random.seed(20260731)
out = []
lens = [0,1,3,55,56,57,63,64,65,111,112,113,127,128,129,255,1000,4096]
data = []
out.append("/* generated by test/mkcryptvec.py - do not hand-edit */")
out.append("static const struct { int len; const char *md5, *s256, *s384, *s512; } VEC[] = {")
for n in lens:
    b = bytes(random.randrange(256) for _ in range(n))
    data.append(b)
    out.append('  { %d, "%s", "%s", "%s", "%s" },' % (
        n, hashlib.md5(b).hexdigest(), hashlib.sha256(b).hexdigest(),
        hashlib.sha384(b).hexdigest(), hashlib.sha512(b).hexdigest()))
out.append("};")
out.append("#define NVEC %d" % len(lens))
out.append("static const unsigned char VECDATA[] = {%s};" %
           ",".join(str(x) for b in data for x in b))
out.append("static const int VECOFF[] = {%s};" %
           ",".join(str(sum(lens[:i])) for i in range(len(lens)+1)))
open(sys.argv[1] if len(sys.argv) > 1 else "host/cryptvec.h", "w").write("\n".join(out) + "\n")
