/*
  PDFRender - crypto vectors.  The hash expectations in cryptvec.h are
  generated by Python hashlib (test/mkcryptvec.py), not written by hand:
  a hand-copied SHA-512 vector was wrong first time round and the code
  was blamed for it.  AES and RC4 use the published FIPS-197 and classic
  test vectors.

  Copyright (c) RISC OS Technologies 2026.
  SPDX-License-Identifier: CDDL-1.0
*/
#include <stdio.h>
#include <string.h>
#include "pdftypes.h"
#include "pdfcrypt.h"
#include "cryptvec.h"
static int fails = 0;
static void chk(const char *n, int len, const u8 *g, const char *w, u32 sz)
{
    char b[257]; u32 i;
    for (i = 0; i < sz; i++) snprintf(b + i*2, 3, "%02x", g[i]);
    if (strcmp(b, w)) { printf("FAIL %s len=%d\n  got  %s\n  want %s\n", n, len, b, w); fails++; }
}
int main(void)
{
    int i; u8 d[64];
    for (i = 0; i < NVEC; i++) {
        const u8 *p = VECDATA + VECOFF[i];
        int n = VEC[i].len;
        pdfmd5(p, n, d);    chk("md5", n, d, VEC[i].md5, 16);
        pdfsha256(p, n, d); chk("sha256", n, d, VEC[i].s256, 32);
        pdfsha384(p, n, d); chk("sha384", n, d, VEC[i].s384, 48);
        pdfsha512(p, n, d); chk("sha512", n, d, VEC[i].s512, 64);
    }
    /* streaming in awkward chunk sizes must equal the one-shot result */
    for (i = 0; i < NVEC; i++) {
        const u8 *p = VECDATA + VECOFF[i];
        int n = VEC[i].len, chunk;
        for (chunk = 1; chunk <= 130; chunk += 7) {
            PdfSha512Ctx c5; PdfSha256Ctx c2; PdfMd5Ctx cm;
            int off;
            pdfsha512_init(&c5); pdfsha256_init(&c2); pdfmd5_init(&cm);
            for (off = 0; off < n; off += chunk) {
                int k = (n - off < chunk) ? n - off : chunk;
                pdfsha512_update(&c5, p + off, k);
                pdfsha256_update(&c2, p + off, k);
                pdfmd5_update(&cm, p + off, k);
            }
            pdfsha512_final(&c5, d); chk("sha512 stream", n, d, VEC[i].s512, 64);
            pdfsha256_final(&c2, d); chk("sha256 stream", n, d, VEC[i].s256, 32);
            pdfmd5_final(&cm, d);    chk("md5 stream", n, d, VEC[i].md5, 16);
        }
    }
    printf(fails ? "%d FAILURES\n" : "all hashlib vectors + streaming pass\n", fails);
    return fails != 0;
}
